In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])

In [3]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [ ]:
# Alternative way to do the same thing with .loc
df.loc[pd.notna(df['salary_year_avg']),'salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [5]:
df['salary_year_avg_next_year']=df['salary_year_avg']*1.03

In [8]:
df[pd.notna(df['salary_year_avg_next_year'])]['salary_year_avg_next_year']

28        112785.00
77        144200.00
92        123600.00
100       235068.66
109        91670.00
            ...
785624    143392.48
785641    154500.00
785648    228531.25
785682    162225.00
785692    162225.00
Name: salary_year_avg_next_year, Length: 22003, dtype: float64

In [14]:
#Alternative way to do the same thing with apply
df_salary=df[pd.notna(df['salary_year_avg'])].copy()

def increase_salary(salary):
    return salary*1.03

df_salary['salary_year_inflated']=df_salary['salary_year_avg'].apply(increase_salary)

In [15]:
df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [17]:
df_salary['salary_year_inflated']=df_salary['salary_year_avg'].apply(lambda salary: salary*1.03)
df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [28]:
#convert string to list 'job_skills'
df['job_skills_list']=df['job_skills'].str.split(',')
df['job_skills_list'].head()

0                                                 None
1    [['r',  'python',  'sql',  'nosql',  'power bi...
2    [['python',  'sql',  'c#',  'azure',  'airflow...
3    [['python',  'c++',  'java',  'matlab',  'aws'...
4    [['bash',  'python',  'oracle',  'aws',  'ansi...
Name: job_skills_list, dtype: object

In [27]:
type(df['job_skills_list'].head())

pandas.core.series.Series

In [25]:
import ast
type(ast.literal_eval(df['job_skills'][1]))

list

In [29]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

df['job_skills']=df['job_skills'].apply(clean_list)

In [31]:
df['job_skills'][1]

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [33]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])
df['job_skills']=df['job_skills'].apply(lambda x: ast.literal_eval(x) if pd.notna(x) else x)

In [37]:
def projected_salary(row):
    if 'Senior' in row['job_title']:
        return row['salary_year_avg']*1.05
    else:
        return row['salary_year_avg']*1.03
        

df_salary['salary_year_inflated']=df_salary.apply(projected_salary,axis=1)
df_salary[['job_title','salary_year_avg','salary_year_inflated']]

,job_title,salary_year_avg,salary_year_inflated
28,CRM Data Specialist,109500.0,112785.00
77,Data Engineer,140000.0,144200.00
92,Remote - Data Engineer - Permanent - W2,120000.0,123600.00
100,"Data Scientist, Risk Data Mining - USDS",228222.0,235068.66
109,Senior Supply Chain Analytics Analyst,89000.0,93450.00
...,...,...,...
785624,Data Analytics Engineer (Hybrid),139216.0,143392.48
785641,Data Engineer,150000.0,154500.00
785648,Director Data Scientist - Commercial Platforms...,221875.0,228531.25
785682,Data Scientist für datengetriebene Entwicklung...,157500.0,162225.00
785692,Data Scientist- Hybrid Work Location,157500.0,162225.00

In [45]:
df_sal=df[pd.notna(df['salary_hour_avg'])].copy()

In [46]:

df_sal['salary_hour_avg'].head()

43     97.5
51     72.5
253    88.0
294    52.5
340    67.5
Name: salary_hour_avg, dtype: float64

In [ ]:
def pedicted(row):
    if 'Senior' in row['job_title']:
        return row['salary_hour_avg']*1.05
    else:
        return row['salary_hour_avg']*1.03

df_sal['salary_rate_inflated']=df_sal.apply(pedicted, axis=1)
df_sal['inflation%']=(df_sal['salary_rate_inflated']/df_sal['salary_hour_avg']-1)*100
df_sal[['job_title','salary_hour_avg','salary_rate_inflated','inflation%']]

,job_title,salary_hour_avg,salary_rate_inflated,inflation%
43,Sr SQL Database Engineer with Data Warehouse /...,97.500000,100.425000,3.0
51,Senior Data Engineer,72.500000,76.125000,5.0
253,Data Engineer,88.000000,90.640000,3.0
294,Business/Data Analyst,52.500000,54.075000,3.0
340,23-00059 BI Data Analysts + Media experience -...,67.500000,69.525000,3.0
...,...,...,...,...
784068,"Manager, Data Engineering",54.420002,56.052602,3.0
784267,Senior Lead Data Engineer - Now Hiring,61.159996,64.217996,5.0
785111,"Health and Civil Data Engineer, Senior - Now H...",61.159996,64.217996,5.0
785476,"Data Scientist, Lead",47.620003,49.048603,3.0
785492,Data Scientist,47.620003,49.048603,3.0

: